package protocol.communication;

public enum PacketType {
    LOGIN,
    LOGIN_FROM_PEER,
    DISCONNECT,
    DISCONNECT_FROM_PEER,
    DISCONNECT_NOTIFICATION,
    REGISTER,
    MESSAGE,
    NEW_USER_NOTIFICATION,
    NEW_RELATION_NOTIFICATION,
    NEW_RELATION,
    DELETE_RELATION,
    DELETE_RELATION_NOTIFICATION,
    GET_RELATIONS,
    PENDING_RELATION_REQUESTS,
    GET_USER_IP
}
